EndOfLine:
 Enabled: false

Metrics/LineLength:
 Max: 150

Metrics/MethodLength:
 Max: 30

Style/GlobalVars:
 Enabled: false

Bundler/OrderedGems:
 Enabled: false

AllCops:
 TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
 Enabled: false

Style/StringLiterals:
 Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Max: 50

Metrics/BlockLength:
  Enabled: true
  Max: 70

Style/HashSyntax:
  Enabled: false
